name: 'Project Updates'
description: 'Action to send the latest changes on a GitHub project to a Slack channel'
inputs:
  project_token:
    description: 'Token with access to read the project'
    required: true
  project_organization:
    description: 'Organization that owns the project'
    required: true
    default: ${{ github.repository_owner }}
  project_number:
    description: 'Project number'
    required: true
  storage_token:
    description: 'Token with access to read and write to the storage repository'
    required: true
    default: ${{ github.token }}
  storage_repository:
    description: 'Repository to store data in'
    required: true
    default: ${{ github.repository }}
  storage_path:
    description: 'File in the repository to store data in, JSON format'
    required: true
  committer_name:
    description: 'Name to commit data changes as'
    required: true
  committer_email:
    description: 'Email for committer'
    required: true
  custom_fields:
    description: 'Custom fields from the project board to use, comma separated'
    required: false
  filter:
    description: 'Filter to apply to the project board, in format `key:value key2:value2`'
    required: false
outputs:
  updates:
    description: 'All updates to be sent to Slack'

runs:
  using: 'node20'
  main: 'dist/index.js'